micronaut:
  application:
    name: cardApiMicronaut
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/card-api-micronaut
    driverClassName: org.postgresql.Driver
    username: card-api
    password: 'card-api'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
com:
  card:
    auth:
      token:
        size: 16
        lifetime: 10