micronaut:
  application:
    name: cardApiMicronaut

  ssl:
    enabled: true
    keyStore:
      path: classpath:keystore.p12
      password: password
      type: PKCS12
    port: 8443

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/card-api-micronaut
    driverClassName: org.postgresql.Driver
    username: card-api
    password: 'card-api'
    schema-generate: CREATE
    dialect: POSTGRES
com:
  card:
    auth:
      token:
        size: 16
        lifetime: 10